CREATE OR REPLACE PROCEDURE SANDBOX_MAIN.PUBLIC.SANDBOX_DROP()
RETURNS BOOLEAN
LANGUAGE SQL
COMMENT='This procedure delete the sanbow when triggered by the task'
EXECUTE AS CALLER
AS 
DECLARE
  OBJECT_TO_DELETE VARCHAR ;
  INFROMATION_CURSOR CURSOR FOR SELECT USER_NAME, EXPIRATION_DATE 
  FROM SANDBOX_MAIN.PUBLIC.SANDBOX_LOG 
  where EXPIRATION_DATE::date<=CURRENT_DATE()::date;
BEGIN
  OPEN INFROMATION_CURSOR;
  FOR INFROMATION_RECORD IN INFROMATION_CURSOR DO
    OBJECT_TO_DELETE := INFROMATION_RECORD.USER_NAME ;
    DROP USER IF EXISTS identifier( :OBJECT_TO_DELETE ) ;
    OBJECT_TO_DELETE := $$SANDBOX_ROLE_$$||INFROMATION_RECORD.USER_NAME ;
    DROP ROLE IF EXISTS identifier(OBJECT_TO_DELETE)   ;
    OBJECT_TO_DELETE := $$SANDBOX_DB_$$||INFROMATION_RECORD.USER_NAME ;
    DROP DATABASE IF EXISTS identifier(OBJECT_TO_DELETE)  ;
    OBJECT_TO_DELETE := $$SANDBOX_WH_$$||INFROMATION_RECORD.USER_NAME ;
    DROP WAREHOUSE IF EXISTS identifier(:OBJECT_TO_DELETE) ;  
  END FOR;
  CLOSE INFROMATION_CURSOR ;
  -- delete the INFROMATION_BEWERBER whose environment is dropped
  delete from SANDBOX_MAIN.PUBLIC.SANDBOX_LOG 
  where EXPIRATION_DATE::date<=CURRENT_DATE()::date ;
  return true ;
END;
